const InspirationalQuotesData = [
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Your time is limited, don't waste it living someone else's life. – Steve Jobs",
  "The best way to predict your future is to create it. – Abraham Lincoln",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "The harder the struggle, the more glorious the triumph. – Swami Sivananda",
  "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "It always seems impossible until it’s done. – Nelson Mandela",
  "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
  "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
  "Our greatest glory is not in never falling, but in rising every time we fall. – Confucius",
  "Don’t let yesterday take up too much of today. – Will Rogers",
  "Strength does not come from physical capacity. It comes from an indomitable will. – Mahatma Gandhi",
  "Tough times never last, but tough people do. – Robert H. Schuller",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "The best revenge is massive success. – Frank Sinatra",
  "Dream big and dare to fail. – Norman Vaughan",
  "Act as if what you do makes a difference. It does. – William James",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
];

export default InspirationalQuotesData;
